filebeat.prospectors:
- input_type: log
  paths:
    - /hostfs/var/lib/docker/containers/*/*.log
  document_type: docker
  json.message_key: log


output.logstash:
  hosts: ["logstash:5044"]
  bulk_max_size: 1024
#  index: filebeat



#logging.level: debug
