global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
#  - job_name: 'prometheus'
#    target_groups:
#      - targets: ['localhost:9090']
  - job_name: 'node-exporter-swarm'
    target_groups:
      - targets: ['192.168.1.128:9100']
  - job_name: 'node-exporter-kubernetes'
    target_groups:
      - targets: ['192.168.1.127:9100']
  - job_name: 'node-exporter-prod'
    target_groups:
      - targets: ['192.168.1.129:9100']

rule_files:
  - 'alert.rules'
